### ISSUE TITLE
Avoid dropping the Redshift table

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/customer-health-scores#2]
Hey there @jwinternheimer! I was taking a look at the code while working on https://github.com/bufferapp/customer-health-scores/issues/1 and wanted to share one small thing with you and check if it makes sense!

Right now, once the model is fitted, we're [dropping the entire table](https://github.com/bufferapp/customer-health-scores/blob/master/generate_scores.R#L155-L156) and recreating it. Since we don't have too much data in there, do you think it could be valuable just appending it? 

Each record in the table will be a `customer_health_score` with an extra field `computed_at`. If we wanted to get the most recent ones we could use a window function to get the last ones. This could also be useful to track the evolution for certain users since we have the predictions in different time points!

Not sure if this all makes sense, just wanted to start a discussion about it. 😄

**Comment by jwinternheimer** [comment]
Hey @davidgasquez, thanks for bringing this up. I'm aware of it, but I think it will be alright as long as the table isn't too big. It's < 10K rows per day, but it will grow over time. I think we should be fine for now. 😄 

The reason I do this is because I haven't found a good way to update a RS table from R - there's an odd syntax issue with S3 somewhere that makes it difficult. 

> This could also be useful to track the evolution for certain users since we have the predictions in different time points!

Yes, we're [doing this](https://github.com/bufferapp/customer-health-scores/blob/abbafcebceb1638fea6935f5fcedd16929371f18/generate_scores.R#L181) already. 😄

**Comment by davidgasquez** [comment]
Ups! I totally missed the `get_historic_data()` function. I know is not easy to bulk insert data into Redshift. I think we can try the current approach although it makes take a lot of time and get killed by Kubernetes. 

One question, couldn't we just `INSERT` the new data without having to `get_historic_data()` first?

Ideally, we should use something that takes care of uploading the new data to S3 as we do in `rsdf`. I found a [blog post about bulk inserting data into Redshift from R](https://www.r-bloggers.com/how-to-bulk-upload-your-data-from-r-into-redshift/) but not sure if it will work!

**Comment by jwinternheimer** [comment]
Cool, I'll give it a shot next week!
